server:
  port: 8082

# 服务名称
spring:
  application:
    name: cloud-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3307/cloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: haozai
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: route
          # 目标服务地址（uri：地址，请求转发后的地址）
            uri: http://localhost:7009/a
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
            predicates:
            ## 转发地址格式为 uri/archive
            - Path=/a/**
  security:
    user:
      name: admin
      password: 123456
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:9000/public/key.json
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug
