server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/aihaozai/config.git
          search-paths: config
      profile: dev
      label: master
      failFast: true





